#!/bin/sh

. ../../shell/chaqum

repeat -c "*/5 * * * * *" -- scan

jobid=$(enqueue -g test -m 3 -- wait)
jobid=$(enqueue -g test -m 3 -- wait)
jobid=$(enqueue -g test -m 3 -- wait)
jobid=$(enqueue -g test -m 3 -- wait)

waitjobs -t 5 -- $jobid >/dev/null

