name: Convert man pages to HTML and deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install mandoc, make
        run: sudo apt-get install mandoc make

      - name: Build man pages
        run:  make -C man DESTDIR=$(pwd)/build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
